## model.R ##

# Get table metadata
GetTableMetadata <- function() {
  result <- list(
    uid = c(label = "UID", value = "", type = "character"),
    medrec = c(label = "Medical Record", value = "", type = "character"),
    SEX = c(label = "Sex", value = "M", type = "factor", levels = "F, M", ordered = FALSE),
    height_raw = c(label = "Height (raw)", value = NA, type = "character"),
    height = c(label = "Height", value = NA, type = "numeric"),
    weight_raw = c(label = "Weight (raw)", value = NA, type = "character"),
    weight = c(label = "Weight", value = NA, type = "numeric"),
    collector = c(label = "Collector", value = "", type = "character"),
    location = c(label = "Location", value = "", type = "character"),
    tstamp = c(label = "Timestamp", value = "", type = "character"),
    birth = c(label = "Birth Date", value = as.character(Sys.Date()), type = "character"),
    image = c(label = "Image Date", value = as.character(Sys.Date()), type = "character"),
    aged = c(label = "Age (days)", value = NA, type = "integer"),
    agey = c(label = "Age (years)", value = NA, type = "numeric"),
    COD = c(label = "Cause of death", value = NA, type = "character"),
    MOD = c(label = "Manner of death", value = NA, type = "chracter"),
    ## long bone measurements
    # femur
    FDL_L = c(label = "FDL_L", value = NA, type = "numeric"),
    FMSB_L = c(label = "FMSB_L", value = NA, type = "numeric"),
    FDB_L = c(label = "FDB_L", value = NA, type = "numeric"),
    FCB_L = c(label = "FCB_L", value = NA, type = "numeric"),
    FIB_L = c(label = "FIB_L", value = NA, type = "numeric"),
    FDL_R = c(label = "FDL_R", value = NA, type = "numeric"),
    FMSB_R = c(label = "FMSB_R", value = NA, type = "numeric"),
    FDB_R = c(label = "FDB_R", value = NA, type = "numeric"),
    FCB_R = c(label = "FCB_R", value = NA, type = "numeric"),
    FIB_R = c(label = "FIB_R", value = NA, type = "numeric"),
    # tibia
    TDL_L = c(label = "TDL_L", value = NA, type = "numeric"),
    TPB_L = c(label = "TPB_L", value = NA, type = "numeric"),
    TMSB_L = c(label = "TMSB_L", value = NA, type = "numeric"),
    TDB_L = c(label = "TDB_L", value = NA, type = "numeric"),
    TDL_R = c(label = "TDL_R", value = NA, type = "numeric"),
    TPB_R = c(label = "TPB_R", value = NA, type = "numeric"),
    TMSB_R = c(label = "TMSB_R", value = NA, type = "numeric"),
    TDB_R = c(label = "TDB_R", value = NA, type = "numeric"),
    # fibula
    FBDL_L = c(label = "FBDL_L", value = NA, type = "numeric"),
    FBDL_R = c(label = "FBDL_R", value = NA, type = "numeric"),
    # humerus
    HDL_L = c(label = "HDL_L", value = NA, type = "numeric"),
    HPB_L = c(label = "HPB_L", value = NA, type = "numeric"),
    HMSB_L = c(label = "HMSB_L", value = NA, type = "numeric"),
    HDB_L = c(label = "HDB_L", value = NA, type = "numeric"),
    HCB_L = c(label = "HCB_L", value = NA, type = "numeric"),
    HIB_L = c(label = "HIB_L", value = NA, type = "numeric"),
    HDL_R = c(label = "HDL_R", value = NA, type = "numeric"),
    HPB_R = c(label = "HPB_R", value = NA, type = "numeric"),
    HMSB_R = c(label = "HMSB_R", value = NA, type = "numeric"),
    HDB_R = c(label = "HDB_R", value = NA, type = "numeric"),
    HCB_R = c(label = "HCB_R", value = NA, type = "numeric"),
    HIB_R = c(label = "HIB_R", value = NA, type = "numeric"),
    # radius
    RDL_L = c(label = "RDL_L", value = NA, type = "numeric"),
    RPB_L = c(label = "RPB_L", value = NA, type = "numeric"),
    RMSB_L = c(label = "RMSB_L", value = NA, type = "numeric"),
    RDB_L = c(label = "RDB_L", value = NA, type = "numeric"),
    RDL_R = c(label = "RDL_R", value = NA, type = "numeric"),
    RPB_R = c(label = "RPB_R", value = NA, type = "numeric"),
    RMSB_R = c(label = "RMSB_R", value = NA, type = "numeric"),
    RDB_R = c(label = "RDB_R", value = NA, type = "numeric"),
    # ulna
    UDL_L = c(label = "UDL_L", value = NA, type = "numeric"),
    UMSB_L = c(label = "UMSB_L", value = NA, type = "numeric"),
    UDL_R = c(label = "UDL_R", value = NA, type = "numeric"),
    UMSB_R = c(label = "UMSB_R", value = NA, type = "numeric"),
    ## dentition
    # dentition maxillary
    max_M1_L = c(label = "max_M1_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    max_M1_R = c(label = "max_M1_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # max_M1_side = c(label = "max_M1_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    max_M2_L = c(label = "max_M2", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    max_M2_R = c(label = "max_M2", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # max_M2_side = c(label = "max_M2_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    max_M3_L = c(label = "max_M3_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    max_M3_R = c(label = "max_M3_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # max_M3_side = c(label = "max_M3_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    max_PM1_L = c(label = "max_PM1_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    max_PM1_R = c(label = "max_PM1_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # max_PM1_side = c(label = "max_PM1_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    max_PM2_L = c(label = "max_PM2_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    max_PM2_R = c(label = "max_PM2_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # max_PM2_side = c(label = "max_PM2_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    max_C_L = c(label = "max_C_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    max_C_R = c(label = "max_C_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # max_C_side = c(label = "max_C_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    max_I1_L = c(label = "max_I1_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    max_I1_R = c(label = "max_I1_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # max_I1_side = c(label = "max_I1_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    max_I2_L = c(label = "max_I2_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    max_I2_R = c(label = "max_I2_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # max_I2_side = c(label = "max_I2_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),

    # dentition mandibular
    man_M1_L = c(label = "man_M1_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    man_M1_R = c(label = "man_M1_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # man_M1_side = c(label = "man_M1_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    man_M2_L = c(label = "man_M2_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    man_M2_R = c(label = "man_M2_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # man_M2_side = c(label = "man_M2_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    man_M3_L = c(label = "man_M3_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    man_M3_R = c(label = "man_M3_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # man_M3_side = c(label = "man_M3_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    man_PM1_L = c(label = "man_PM1_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    man_PM1_R = c(label = "man_PM1_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # man_PM1_side = c(label = "man_PM1_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    man_PM2_L = c(label = "man_PM2_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    man_PM2_R = c(label = "man_PM2_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # man_PM2_side = c(label = "man_PM2_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    man_C_L = c(label = "man_C_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    man_C_R = c(label = "man_C_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # man_C_side = c(label = "man_C_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    man_I1_L = c(label = "man_I1_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    man_I1_R = c(label = "man_I1_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # man_I1_side = c(label = "man_I1_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),
    man_I2_L = c(label = "man_I2_L", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    man_I2_R = c(label = "man_I2_R", value = "", type = "factor", levels = paste(1:13, collapse = ", "), ordered = TRUE),
    # man_I2_side = c(label = "man_I2_side", value = "", type = "factor", levels = paste(c("M", "L", "R"), collapse = ", "), ordered = FALSE),

    # epiphyseal fusion and ossification
    # femur
    FH_EF_L = c(label = "FH_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    FGT_EF_L = c(label = "FGT_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    FLT_EF_L = c(label = "FLT_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    FDE_EF_L = c(label = "FDE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),

    FH_EF_R = c(label = "FH_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    FGT_EF_R = c(label = "FGT_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    FLT_EF_R = c(label = "FLT_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    FDE_EF_R = c(label = "FDE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    # tibia
    TPE_EF_L = c(label = "TPE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    TDE_EF_L = c(label = "TDE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),

    TPE_EF_R = c(label = "TPE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    TDE_EF_R = c(label = "TDE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    # fibula
    FBPE_EF_L = c(label = "FBPE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    FBDE_EF_L = c(label = "FBDE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),

    FBPE_EF_R = c(label = "FBPE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    FBDE_EF_R = c(label = "FBDE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    # humerus
    HH_Oss_L = c(label = "HH_Oss_L", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HGT_Oss_L = c(label = "HGT_Oss_L", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HLT_Oss_L = c(label = "HLT_Oss_L", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HPE_EF_L = c(label = "HPE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    HC_Oss_L = c(label = "HC_Oss_L", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HT_Oss_L = c(label = "HT_Oss_L", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HLE_Oss_L = c(label = "HLE_Oss_L", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HCE1_EF_L = c(label = "HCE1_EF_L", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HCE2_EF_L = c(label = "HCE2_EF_L", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HDE_EF_L = c(label = "HDE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    HME_EF_L = c(label = "HME_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),

    HH_Oss_R = c(label = "HH_Oss_R", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HGT_Oss_R = c(label = "HGT_Oss_R", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HLT_Oss_R = c(label = "HLT_Oss_R", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HPE_EF_R = c(label = "HPE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    HC_Oss_R = c(label = "HC_Oss_R", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HT_Oss_R = c(label = "HT_Oss_R", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HLE_Oss_R = c(label = "HLE_Oss_R", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HCE1_EF_R = c(label = "HCE1_EF_R", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HCE2_EF_R = c(label = "HCE2_EF_R", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    HDE_EF_R = c(label = "HDE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    HME_EF_R = c(label = "HME_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    # radius
    RPE_EF_L = c(label = "RPE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    RDE_EF_L = c(label = "RDE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),

    RPE_EF_R = c(label = "RPE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    RDE_EF_R = c(label = "RDE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    # ulna
    UPE_EF_L = c(label = "UPE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    UDE_EF_L = c(label = "UDE_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),

    UPE_EF_R = c(label = "UPE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    UDE_EF_R = c(label = "UDE_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    # other
    CT_EF_L = c(label = "CT_EF_L", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),
    CT_EF_R = c(label = "CT_EF_R", value = "", type = "factor", levels = paste(c(0:2, 23, 3:4), collapse = ", "), ordered = TRUE),

    CC_Oss = c(label = "CC_Oss", value = "", type = "factor", levels = paste(c(0:8), collapse = ", "), ordered = TRUE),
    TC_Oss = c(label = "TC_Oss", value = "", type = "factor", levels = paste(c(0:7), collapse = ", "), ordered = TRUE),

    ISPR_EF_L = c(label = "ISPR_EF_L", value = "", type = "factor", levels = paste(c(0:2), collapse = ", "), ordered = TRUE),
    ISPR_EF_R = c(label = "ISPR_EF_R", value = "", type = "factor", levels = paste(c(0:2), collapse = ", "), ordered = TRUE),
    ILIS_EF_L = c(label = "ILIS_EF_L", value = "", type = "factor", levels = paste(c(0:2), collapse = ", "), ordered = TRUE),
    ILIS_EF_R = c(label = "ILIS_EF_R", value = "", type = "factor", levels = paste(c(0:2), collapse = ", "), ordered = TRUE),
    PC_Oss_L = c(label = "PC_Oss_L", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE),
    PC_Oss_R = c(label = "PC_Oss_R", value = "", type = "factor", levels = paste(c(0:1), collapse = ", "), ordered = TRUE)
  )
  return(result)
}
